### ISSUE TITLE
Function call parameters shall have a space before the start of each of the parameter except the first

### ISSUE THREAD

**Issue by shivanalla** [triandicAnt/Formatme#14]
1. Function call parameters shall have a space before the start of each of the parameter except the first; In other words, spaces shall be added after the comma if not already added. 
(should also work with scenarios where string parameters might contain comma)

2. Delete extra spaces if present (spaces after the mention of the parameter, i.e. before a comma)

Ex: 
```
//bad
method1(param1,param2 ,param3); 
//good
method1(param1, param2, param3);

//original
method1(param1,'I contain comma,don\'t I ?',param3); 
//make sure this doesn't happen
method1(param1, 'I contain comma, don\'t I ?', param3)
```

**Comment by triandicAnt** [comment]
method(param1,'a,b');
