### ISSUE TITLE
Add space after comment (`//`) and Ignore urls(starting with http|s) while formatting.

### ISSUE THREAD

**Issue by triandicAnt** [triandicAnt/Formatme#18]
Add space after comment start `// `
bad : `//Hey, I am a comment`
good : `// Hey, I am a comment`
Ignore
```
http://www.fixmenow.com
```

**Comment by malloryw** [comment]
I don't think it's necessary to add a space after `//` in comments. Neither way is "wrong"
```
//this is ok
// this is also ok. 
```
