### ISSUE TITLE
Convert upper case SOQL keywords to lowercase

### ISSUE THREAD

**Issue by malloryw** [triandicAnt/Formatme#3]
Example: 
```
// wrong
List<Account> accs = [SELECT Id FROM Account 
                      WHERE Name = 'Test'];
// should be
List<Account> accs = [select Id from Account
                      where Name = 'Test'];
```

Regex solutions would be something like:
- r'\[SELECT ' ==> r'[select '
-- make sure there is a space after the word 'SELECT '
- r'\[select (\s|\w|,|\(|\))+ FROM ' => custom function
-- make sure this rule is after the rule above
-- the stuff between 'select' and 'FROM' represent whitespace, words, number, and commas and parenthesis. 
-- make sure there is 1 space before AND after ' FROM ' to completely isolate the keyword.
-- custom function gets all text before 'FROM' and returns a new string with lower case 'from'
- r'\[select (\s|\w|,|\(|\))+ from (\s|\w)+ WHERE ' => custom function
-- make sure there is 1 space before AND after ' WHERE ' to completely isolate the keyword.
-- custom function gets all text before 'WHERE' and returns a new string with lower case 'where'
- r'\[select (\s|\w|,|\(|\))+ from (\s|\w|\W)+ LIMIT ' => custom function
- r'\[select (\s|\w|,|\(|\))+ from (\s|\w|\W)+ ORDER BY ' => custom function
- r'\[select (\s|\w|,|\(|\))+ from (\s|\w|\W)+ GROUP BY ' => custom function

```
// sample complicated query verified here https://regex101.com/
[SELECT Id, count(Id), NumberField2
	FROM SAMPLE__c
        WHERE Id = :Utils.something() LIMIT 29];
```

**Comment by triandicAnt** [comment]
Can we do case insensitive whole word search and replace with desired word like : 
```
    (r'(?i)\bSELECT\b *' , r'select '),
    (r'(?i)\bFROM\b *' , r'from '),
    (r'(?i)\bWHERE\b *' , r'where '),
    (r'(?i)\bLIMIT\b *' , r'limit '),
    (r'(?i)\bGROUP by\b *' , r'group by'),
    (r'(?i)\bORDER by\b *' , r'order by'),
    (r'(?i)\bHAVING\b *' , r'having'),

```

`\b` is for boundary and `(?i)` is case insensitive.

**Comment by malloryw** [comment]
I tested on regex101.com. The regex in your last comment passes all the weird edge scenarios I can think of. We can go with this solution. It's short and simple and gets the job done.

Only question is, will this slow down performance? The script will do excess work when it converts 'select -> 'select' (no difference)

**Comment by triandicAnt** [comment]
the apex files are mostly on an average of less than 1000 lines and those contains soql keywords on an average of 20-30. So performance should not be that bad.
