### ISSUE TITLE
Ignore formatting if regex detects a formatting mistake that is encased in string or comments

### ISSUE THREAD

**Issue by malloryw** [triandicAnt/Formatme#7]
The rule on line #71 is too generic. Here is an example when it formats when we don't want it to:
```
List<String> splitList = string.split(','); // this will get converted to ', ' which could cause problems
```
One way to bypass this is to ignore commas if they are surrounded by quotes.

Similarly, text that is commented out should also be ignored. (single line comment // and block comment /* ... */ )

**Comment by triandicAnt** [comment]
the comma problem has been taken care of.  To bypass we just have to add in the ignore set like : `(\, *)[^\'\,\'|\w]`
